{% set name = "nbmerge" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f432797ee685ed495a2daa4dbb76e2b52028d2c3a38142b523bb5cb832df0882

build:
  number: 0
  noarch: python
  entry_points:
    - nbmerge = nbmerge:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - nbformat

test:
  imports:
    - nbmerge

about:
  home: https://github.com/jbn/nbmerge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to merge / concatenate Jupyter (IPython) notebooks
  description: A tool to merge / concatenate Jupyter (IPython) notebooks

extra:
  recipe-maintainers:
    - timkpaine
